### PR TITLE
Add a "used by X" section to the front page

### LINKED ISSUE #155: Add a list of companies using Raku
I propose we add a list of companies using Raku to the raku.org startpage. In spirit similar to what many other (commercial) websites do to. (e. g. [Jira](https://www.atlassian.com/software/jira), [Holiday API](https://holidayapi.com/), and many more)

Given we actually find enough companies (I aim for at least 5), this can help to communicate that Raku is mature enough to be used in production and does have a userbase. This supports the follower effect: "If others use Raku it can't be that bad."

This ticket doubles as a call for companies using Raku and are willing to allow us to list them as using Raku on our frontpage.
So: If you work at a company that uses Raku, please do ask for permission in your company and speak up in this ticket.

There already are positive replies of:

- Edument
- Atikon

### PR DESCRIPTION
**Pull request by patrickbkr**
It seems I can't add people as reviewers that are not somehow part of the GitHub project. So I'm pinging the bunch I can't add as reviewers.

@wtwt5237 @scmorrison @vedang Please review.

Screenshot_20210310_211453

Fixes #155

### CODE REVIEW

**Comment by vrurg** [comment]
It feels to me that the section is better be visually separated from the rest of the page. Perhaps enclosed into own "window"? Feel free to ignore my opinion if disagree. :)

**Comment by vedang** [comment]
LGTM

**Comment by patrickbkr** [comment]
Screenshot_20210323_194456
Here is a version with a block around.
Please give a :thumbsup: if you like this version better and a :thumbsdown: if you like the original version in the first comment better.

**Comment by patrickbkr** [comment]
@wtwt5237 @scmorrison @jnthn @niner @zaucker @p6steve
You didn't yet provide any feedback yet. As all of you were gave their initial approval over on the issue, I'll just leave this open a few more days and then assume silent approval and move forward with this should no objections arise.

**Comment by wtwt5237** [comment]
@patrickbkr, I approve. This looks great! Thanks so much for the effort!

**Review by niner — APPROVED** [review]

**Comment by p6steve** [comment]
I approve

~ Steve Roe

***@***.***

**Review by jnthn — APPROVED** [review]

**Review by vrurg — APPROVED** [review]

**Review by lizmat — APPROVED** [review]

**Comment by scmorrison** [comment]
I approve. Looks great.

**Review by scmorrison — APPROVED** [review]

**Pull request merged**
