### PR TITLE
More Perl 6 -> Raku changes

### PR DESCRIPTION
**Pull request by hankache**

### CODE REVIEW

**Comment by hankache** [comment]
Why can't I merge this PR anymore?

**Comment by JJ** [comment]
> Why can't I merge this PR anymore?

No idea. I guess it's a consequence of the restructuring of the repos. Maybe @AlexDaniel knows.

**Comment by AlexDaniel** [comment]
Should be fixed now.

**Comment by hankache** [comment]
Thanks @JJ @AlexDaniel

**Pull request merged**
