### PR TITLE
Added remaining bots on whateverable list

### PR DESCRIPTION
**Pull request by finanalyst**

### CODE REVIEW

**Comment by AlexDaniel** [comment]
By any chance can we simplify that section by simply linking to https://github.com/Raku/whateverable/wiki? Most bots tend to either just die or get replaced with improved whateverable-based versions. Looking at the list, the only non-whateverable bot you can talk to is `camelia`. Other bots like `Geth`, `cpan-raku` and `travis-ci` are simply announcers.

**Comment by coke** [comment]
While I agree I'd rather keep the list in one place, not two, I'm not opposed to accepting this until we sort that out.

If you can update the links so they are for Raku, not perl6, we can merge this.

**Comment by 2colours** [comment]
I would assume that with #175 , this can be closed without merging.

**Comment by coke** [comment]
> I would assume that with #175 , this can be closed without merging.

I think you're right - @finanalyst, please reopen if I'm reading this wrong.

**Pull request closed without merging**
