### PR TITLE
Change the "Download" page to "Install" for a better non-Linux or new user experience

### PR DESCRIPTION
**Pull request by tbrowder**
+ added a new button: Rakubrew.org link

+ emphasized the new button as recommended for new or non-linux users

### CODE REVIEW

**Comment by patrickbkr** [comment]
This is strongly promoting Rakubrew over the other installation methods. I guess many people would not even have a look at what other options there are. (e.g. there are MSI installers for Windows)
Can you remove that part and keep the "Downloads" -> "Install" bits?

**Comment by tbrowder** [comment]
I'll have to first evaluate the use of the various methods for installing Rakudo on Windows. Then I'll take another look at this PR.

**Comment by tbrowder** [comment]
See the slight word change.

**Comment by patrickbkr** [comment]
@tbrowder I think we need to discuss https://github.com/Raku/raku.org/issues/73#issuecomment-1596904623 some more.

The raku.org and rakudo.org pages have a long history of providing only a partial and opinionated view on installation options. The mess that once was there was a result of one by one adding installation options to different places according to individual preference and what an individual deemed the best option. Preferences differed. People complained that having more than one place that lists installation options creates confusion as one would always have to look in both places to get a full understanding.

Adding a specific installation option to raku.org is especially problematic as every time someone just goes for the recommeded option they will never have seen or even know that an overview of available installation options exists.

I do recognize that the way things currently are is not ideal. Especially:

- People get confused by rakudo.org looking entirely different from raku.org. "Did I click wrong? Is this even related?"
- People get confused by the amount of differently named "official" names they stumble upon. There was a time when people first read about Raku on raku.org, then were sent over to rakudo.org to learn about Rakudo and then were told what they needed to download was Rakudo Star. On the way a few bits of NQP and MoarVM and the other backends were sprinkled in. (This has improved a lot.)

But I believe that improving at explaining the complexity is more sustainable than trying to hide that complexity. Thus I still opose adding any specific installation options to raku.org.

**Comment by tbrowder** [comment]
I surrender.

**Pull request closed without merging**
