### PR TITLE
Fix links and perl6 to raku

### PR DESCRIPTION
**Pull request by sumanstats**
edit raku-overview image

+ change perl6 to raku and p6 to raku
+ Parrot is legacy, but still is in the image

---

Perl 5 to only Perl

With renaming there is no other perl version, perl 5 is perl now, no
ambiguity

---

Fix typo

try --> trying grammar

---

Remove smoke testing header

The link does not point to anything meaningful, it just points to a
basic server

---

Fix the links

+ fix the links of most wanted modules, Roast, nqp

---

Add raku pod in Y minutes link for newcomers

---

Add repl.it RAKU compiler online

+ repl.it has the most recent raku version
+ remove ideaone REPL, as the current ideaone does not support raku, it
  supports Perl only

---

fix the link for raku questions in SO

---

fix link for emacs mode for raku

---

unify the IRC chat link

### CODE REVIEW

**Comment by patrickbkr** [comment]
You could replace "parrot" with "MoarVM" or even better "MoarVM, JVM or JS" in the image. That would reflect the current state of things.

Mildew and Sprixel are only of historic interest, similar to Parrot. I think it's better to remove those.

**Comment by sumanstats** [comment]
See if it looks godd. Cleaned up. Removed historical mildew, sprixel and parrot.

**Comment by patrickbkr** [comment]
Looking really good. Can this be merged now?

**Comment by sumanstats** [comment]
> Looking really good. Can this be merged now?

Sure.

**Pull request merged**
